apiVersion: v1
kind: Service
metadata:
  name: {{ template "karaf.fullname" . }}
  labels:
    app: {{ template "karaf.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    {{- range $service := .Values.services }}
    - port: {{ $service.externalPort }}
      targetPort: {{ $service.internalPort }}
      protocol: TCP
      name: {{ $service.name }}
    {{- end }}
  selector:
    app: {{ template "karaf.name" . }}
    release: {{ .Release.Name }}
